---
# Source: sonarqube/charts/mysql/templates/secrets.yaml
apiVersion: v1
kind: Secret
metadata:
  name: sonarqube-mysql
  labels:
    app.kubernetes.io/name: mysql    
    app.kubernetes.io/instance: sonarqube
    app.kubernetes.io/managed-by: Helm
  namespace: sonarqube
type: Opaque
data:
  mysql-password: "dGVzdDEyMzRlCg="

# Source: sonarqube/templates/secret.yaml
---
apiVersion: v1
kind: Secret
metadata:
  name: sonarqube-sonarqube-monitoring-passcode
  labels:
    app: sonarqube
    chart: sonarqube-1.1.9_137
    release: sonarqube
    heritage: Helm
  namespace: sonarqube
type: Opaque
data:
  SONAR_WEB_SYSTEMPASSCODE: "ZGVmaW5lX2l0"