apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deploy
  namespace: sonarqube
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:13.10
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: 5432
              name: postgres
          envFrom:
            - configMapRef:
                name: postgres-config
          volumeMounts:
            - mountPath: /var/lib/postgresql/data             
              name: postgredb
          env:
           - name: PGDATA
             value: /var/lib/postgresql/data/pgdata
      volumes:
        - name: postgredb
          persistentVolumeClaim:
            claimName: postgres-pv-claim